### ISSUE TITLE
What is the difference between new_mask and shadow_mask in the training process?

### ISSUE THREAD

**Issue by mxz2013** [bcmi/Object-Shadow-Generation-Dataset-DESOBA#20]
Dear authors,

Could you please let me know the difference between the new_mask and shadow_mask in the training process? 

    --bg_shadow_path $bg_shadow_path\
    --new_mask_path $new_mask_path\
Thank you very much for your work!

Best regards,

Sky

**Comment by hy-zpg** [comment]
Hi, the new_mask is calculated from the difference between the shadow image and its deshadowed image, while the shadow_mask is provided by SOBA dataset. Since the deshadowed image is obtained by manual removing technique, which may be introduce a little difference from the shadow_mask provided by SOBA dataset.

**Comment by mxz2013** [comment]
Hello, Thank you very much for your explanation and your great work!
